language: node_js
node_js:
    - node
    - 10
    - 8
cache: npm

script: npm run coverage

notifications:
    - emails: false

after_success:
    - bash <(curl -s https://codecov.io/bash) -t=CODECOV
